### PR TITLE
Run conformance tests in parallel

### PR DESCRIPTION
**Pull request by scothis**

### CODE REVIEW

**Comment by sadlerap** [comment]
Not sure about the test failures, AFAICT `requirements.txt` is present in that commit.

Also, you might be interested in [this PR](https://github.com/servicebinding/conformance/pull/58) (hadn't noticed `behavex` had got a new release).  Between parallel testing landing and a few other things, I'm tempted to cut a `v0.3.0` release.

**Comment by scothis** [comment]
@sadlerap I modified the working dir, the script is looking for requirements.txt in the current dir rather than the dir relative to the script. I wanted to try out the new stuff before we tag a release, but I'd like to have a tag before we merge this PR.

**Comment by sadlerap** [comment]
I'll cut a new release once this passes.

**Comment by sadlerap** [comment]
I've cut https://github.com/servicebinding/conformance/releases/tag/v0.3.0

**Review by sadlerap — APPROVED** [review]

**Pull request merged**
