### PR TITLE
Use conformance 0.2

### PR DESCRIPTION
**Pull request by scothis**
Signed-off-by: Scott Andrews <andrewssc@vmware.com>

### CODE REVIEW

**Review by sadlerap — APPROVED** [review]
LGTM, provided CI passes.

**Comment by scothis** [comment]
Good news: CI passed
Bas news: CI takes 20+ minutes longer with 0.2

We should look at parallelizing the conformance tests, there's no reason they need to be sequential (other than the logs are easier to follow)

**Comment by scothis** [comment]
Spoke too soon. There's a flaky test that failed in the push that passed in the PR build

https://github.com/scothis/service-binding-controller/actions/runs/3652073282/jobs/6170243394

**Comment by sadlerap** [comment]
Hmmmm, not sure I like flakiness in these tests.  Looking in the logs, there seem to be a bunch of errors getting reported (such as [this one on the failing test](https://github.com/scothis/service-binding-controller/actions/runs/3652073282/jobs/6170243394#step:15:5162)); are those intentional?

I've filed [an issue for tracking performace problems](https://github.com/servicebinding/conformance/issues/37); there's definitely some improvements that can be made.  1hr runtime for conformance tests aren't great.

**Comment by scothis** [comment]
I see two common errors, both benign:
1. The "unable to sync" errors with the caused "stop processing SubReconcilers, without returning an error" needs to be suppressed. It's an expected case and not an actual error. The cause is the case where the webhook was intercepting the request that was applying the binding. I think this is what you linked to, deep links into large logs get wonky.
2. optimistic lock failures when updating a resource that was mutated under us.

Was there another error you were seeing?

**Comment by sadlerap** [comment]
nope, I wasn't sure if those were intentional or not, sorry for the confusion.

**Pull request merged**
